### ISSUE TITLE
It only returns the first 100 of the playlist

### ISSUE THREAD

**Issue by pabloleban** [CodeDotJS/youtube-playlist#11]
Im trying a big playlist (https://www.youtube.com/watch?v=Aw2w9vQ-ZMw&list=PLYtz7wWLjIVjmUYkrvaxMqnHjsHgpP7Fx) which more or less 155 videos and it's only giving me the first 100 videos. Is this a limitation that can be fixed?

**Comment by CodeDotJS** [comment]
The playlist is getting scrapped with the help of [`cheerio`](http://npmjs.com/package/cheerio). YouTube only returns __>=100 videos__ from the playlist during the initial load of the page. To scrap further, you need to scroll down and grab the rest of the contents.

This is indeed a limitation which can't be fixed in this `module`.
