### ISSUE TITLE
Why use this library and not Pufetch?

### ISSUE THREAD

**Issue by elieobeid7** [CodeDotJS/youtube-playlist#6]
Why use this one and not pufetch? What's the difference? 

https://github.com/CodeDotJS/pufetch

**Comment by CodeDotJS** [comment]
I'll answer for the both #5 and #6 at one place ~ 

[`Pufetch`](https://github.com/CodeDotJS/pufetch) is a command line tool which you __can not__ use programatically in your application. 

Suppose you are building an electron app to download contents of the playlist and you need to fetch the urls to make your work easier, in that case, you can either manually scrape the urls (that would be similar to re-writing [`youtube-playlist`](https://github.com/CodeDotJS/youtube-playlist)), use the YouTube API (a little bit of complicacy as things might get confusing just for doing some simple task), or just `require` this module to do the same thing (easy). 

~ __`CASE 1`__
```js
const ytlist = require('youtube-playlist');

const playlistUrl = 'x';

ytlist(playlistUrl, 'url').then(res => {
  console.log(res);
  // do something with the data in your app
});
```

~ __`CASE 2`__

```js
$ pufetch --fetch <url>

// somePlaylistContent
```

In the second case, you can manually copy-paste or export the url, just in case you need to save the urls 
 (along with their ids and names) for yourself or for any other purpose, but there is no way you can 
`$ pufetch --fetch <url>` in your application. 

This module is an interface through which you can use it the way you want. For example, suppose you are building another app where you only need to find the ids of all the content available in the playlist, you can ~

```js
ytlist(playlistUrl, 'id').then(res => {
  console.log(res);
  // do something with the ids
});
```

One more thing, __`Pufetch`__ doesn't use this module because it was written way before I felt the need of writing this module. 

The main motive behind creating this module was to avoid YouTube API, and also there were no other modules which did the exact thing similar to this one. 

__Coming to the another part__

> I don't see anywhere that this library requires a Youtube API key or a client ID, so I want to ask if it require one of those and where to use them?

The module is not dependent upon the YouTube API, so it doesn't require any key or token. If you look into the code, it's all just scrapping the web-page to extract the data. You don't need anything extra to use this module. 

> If it doesn't require them, then is there a limit for the usage or limit for number of users?

- __Limit for the usage__ - I'm not aware of the maximum number of requests you can make in a minute. 

- __Limit for number of users__ - There is no limit for that. For example, if 1000s of people run this module at the same time, the requests that will be sent to YouTube will be from the different IP addresses, which is totally fine. Make it millions, and still things will be completely normal.

**Comment by elieobeid7** [comment]
Awesome thank you.
